# Generated by Django 2.0.7 on 2019-09-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_assetaform_assetbform'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetaform',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetaform',
            name='wide',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
