# Generated by Django 2.0.7 on 2019-12-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20191001_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('inspector', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_date', models.DateTimeField(blank=True, null=True)),
                ('oci', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspection',
            },
        )
    ]
