# Generated by Django 2.0.7 on 2019-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_auto_20191203_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='asset_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
