# Generated by Django 2.0.7 on 2019-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20191203_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='assetId',
            field=models.CharField(db_column='asset_id', default='A-0001', max_length=255),
            preserve_default=False,
        )
    ]
